### ISSUE TITLE
Solution exception: Cant convert object Newtonsoft.Json.Linq.JValue to type Newtonsoft.Json.Linq.JProperty.

### ISSUE THREAD

**Issue by joesvdh1** [cityjson/RhinoCityJSON#1]
While trying to read a JSON file in Grasshopper, I get a solution exception which says; can't convert Newtonsoft.Json.Linq.JValue to type Newtonsoft.Json.Linq.JProperty. The JSON file was taken from the 3D basisvoorziening.

![image](https://github.com/cityjson/RhinoCityJSON/assets/93843811/f0caf4a9-d86b-41a7-8342-dfbdbf3555cb)

**Comment by jaspervdv** [comment]
Sorry for the late response. However, this issue should be resolved in the new version that has just been pushed. It will be posted to F4R later this month.
