### ISSUE TITLE
compatibility 3DBAG 

### ISSUE THREAD

**Issue by maartjedamen** [cityjson/RhinoCityJSON#3]
Hi, thank you for this plugin! As mentioned, it is not updated for the CityJSON 2.0 yet, which means it is not compatible with the currently available downloads from 3DBAG. Do you have an indication as to when this update would be implemented, and the plugin will work as intended again?

**Comment by jaspervdv** [comment]
Hey there,

Could you elaborate on which parts of the plugin do not work as intended in 0.6.5? The support for 2.0 has indeed not been officially tested, but I believe it should function with most basic files, like 3DBAG. However, you might have come across some issues i missed

**Comment by maartjedamen** [comment]
Ah, I completely overlooked the newest update, after the update it does indeed work as intended, thank you. mistake on my side!
